-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 13:57:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agent` (
  `id` INT NOT NULL,
  `agent_fname` VARCHAR(45) NULL DEFAULT NULL,
  `agent_lname` VARCHAR(45) NULL DEFAULT NULL,
  `agent_cnum` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `cus_fname` VARCHAR(45) NULL DEFAULT NULL,
  `cus_lname` VARCHAR(45) NULL DEFAULT NULL,
  `cus_cnum` VARCHAR(45) NULL DEFAULT NULL,
  `cus_count` VARCHAR(45) NULL DEFAULT NULL,
  `cus_type` VARCHAR(45) NULL DEFAULT NULL,
  `agent_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_agent_idx` (`agent_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_agent`
    FOREIGN KEY (`agent_id`)
    REFERENCES `mydb`.`agent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photographer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photographer` (
  `id` INT NOT NULL,
  `photo_com` VARCHAR(45) NULL,
  `photo_package` VARCHAR(45) NULL,
  `photo_crew` INT NULL,
  `photo_cnum` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caterer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caterer` (
  `id` INT NOT NULL,
  `cat_com` VARCHAR(45) NULL,
  `cat_crew` INT NULL,
  `cat_pack` VARCHAR(45) NULL,
  `cat_lead` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `id` INT NOT NULL,
  `man_fname` VARCHAR(45) NULL,
  `man_lname` VARCHAR(45) NULL,
  `man_cnum` INT NULL,
  `man_sector` VARCHAR(45) NULL,
  `Photographer_id` INT NULL,
  `Caterer_id` INT NULL,
  PRIMARY KEY (`id`, `Photographer_id`, `Caterer_id`),
  INDEX `fk_manager_Photographer1_idx` (`Photographer_id` ASC) VISIBLE,
  INDEX `fk_manager_Caterer1_idx` (`Caterer_id` ASC) VISIBLE,
  CONSTRAINT `fk_manager_Photographer1`
    FOREIGN KEY (`Photographer_id`)
    REFERENCES `mydb`.`Photographer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manager_Caterer1`
    FOREIGN KEY (`Caterer_id`)
    REFERENCES `mydb`.`Caterer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` INT NOT NULL,
  `cus_fname` VARCHAR(45) NULL DEFAULT NULL,
  `cus_lname` VARCHAR(45) NULL DEFAULT NULL,
  `id` VARCHAR(45) NULL DEFAULT NULL,
  `res_date` VARCHAR(45) NULL DEFAULT NULL,
  `res_event` VARCHAR(45) NULL DEFAULT NULL,
  `res_venue` VARCHAR(45) NULL DEFAULT NULL,
  `customer_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`),
  INDEX `fk_reservation_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_reservation_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Extra` (
  `id` INT NOT NULL,
  `extra_cnum` INT NULL,
  `extra_fname` VARCHAR(45) NULL,
  `extra_lname` VARCHAR(45) NULL,
  `manager_id` INT NOT NULL,
  `manager_Photographer_id` INT NOT NULL,
  `manager_Caterer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`, `manager_Photographer_id`, `manager_Caterer_id`),
  INDEX `fk_Extra_manager1_idx` (`manager_id` ASC, `manager_Photographer_id` ASC, `manager_Caterer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Extra_manager1`
    FOREIGN KEY (`manager_id` , `manager_Photographer_id` , `manager_Caterer_id`)
    REFERENCES `mydb`.`manager` (`id` , `Photographer_id` , `Caterer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
